### ISSUE TITLE
Global perms

### ISSUE THREAD

**Issue by Pandemonious** [Brambles-cat/AdvancedChorusFruit#3]
Hello. Love this mod, hope to see it alive again. I see global permissions are next on your to-do list :)

**Comment by Brambles-c** [comment]
Thank you for using my plugin! Default permissions are finished and included in the latest release. It'll soon be on CurseForge as well after it's been reviewed 👍

**Comment by Pandemonious** [comment]
Just noticed this before you replied. Can't wait to test it out later today.

Just an FYI though - when I said global perms, I meant like an actual permission that I can set to true or false in permissions.yml or luckperms or whatever, and not having it in the .json

That being said, if I can set default perms now, that will still help a lot regardless. I'll report back to you later once I get a chance to run it

**Comment by Brambles-c** [comment]
Huh, had no idea luckperms existed before today. But yeah, since it seems widely used, I'll likely make another update soon with support for it and make the current permission system optional in the cases when that plugin isn't used. Thanks for the feedback 👍
